<?php

namespace AppBundle\Repository;

/**
 * GB_carRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GB_carRepository extends \Doctrine\ORM\EntityRepository
{


    public function searchMatchingCars($searchText)
    {
        return $this->createQueryBuilder('c')
           ->where('c.cMake LIKE :input OR c.cModel LIKE :input OR c.cPrice LIKE :input OR c.cMileage LIKE :input')               
           ->setParameter('input', '%' .$searchText.'%')
           ->setMaxResults(10)
           ->orderBy('c.cModel', 'ASC')
           ->getQuery()
           ->getResult();
    }


}
