<?php

namespace AppBundle\Repository;

/**
 * GB_modelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GB_modelRepository extends \Doctrine\ORM\EntityRepository
{
}
