<?php

namespace AppBundle\Repository;

/**
 * GB_testimonialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GB_testimonialRepository extends \Doctrine\ORM\EntityRepository
{
}
